version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: sportfeeds-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - sportfeeds

  mongodb:
    image: mongo:8.0
    container_name: sportfeeds-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: SportFeeds
    volumes:
      - mongodb_data:/data/db
    networks:
      - sportfeeds

volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  sportfeeds:
    driver: bridge
